-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.airlines
(
    airline_name character(100) NOT NULL,
    logo character(100) NOT NULL,
    country_code character(100) NOT NULL,
    PRIMARY KEY (airline_name)
);

CREATE TABLE IF NOT EXISTS public.plane
(
    plane_number integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    airline character(100) NOT NULL,
    seating_capacity integer NOT NULL,
    PRIMARY KEY (plane_number)
);

CREATE TABLE IF NOT EXISTS public.schedule
(
    trip_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    "IATA" character(3) NOT NULL,
    departure_timestamp timestamp without time zone NOT NULL,
    base_fare integer NOT NULL,
    flight_number integer NOT NULL,
    PRIMARY KEY (trip_id)
);

CREATE TABLE IF NOT EXISTS public.airports
(
    "IATA" character(3) NOT NULL,
    airport_name character(100) NOT NULL,
    longitude point NOT NULL,
    city character(100) NOT NULL,
    PRIMARY KEY ("IATA")
);

CREATE TABLE IF NOT EXISTS public.tickets
(
    ticket_number integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
    purchase_timestamp timestamp without time zone NOT NULL,
    ticket_price integer NOT NULL,
    user_uid character(128),
    trip_id integer,
    PRIMARY KEY (ticket_number)
);

ALTER TABLE IF EXISTS public.plane
    ADD FOREIGN KEY (airline)
    REFERENCES public.airlines (airline_name) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.schedule
    ADD FOREIGN KEY ("IATA")
    REFERENCES public.airports ("IATA") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.schedule
    ADD FOREIGN KEY (flight_number)
    REFERENCES public.plane (plane_number) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tickets
    ADD FOREIGN KEY (trip_id)
    REFERENCES public.schedule (trip_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;